files: ^packages/core/minos-microservice-saga/

repos:
    -   repo: local
        hooks:
            -   id: minos-microservice-saga-install
                pass_filenames: false
                name: Install minos-microservice-saga dependencies
                entry: make --directory=packages/core/minos-microservice-saga install
                language: system

            -   id: minos-microservice-saga-reformat
                pass_filenames: false
                name: Reformat minos-microservice-saga package
                entry: make --directory=packages/core/minos-microservice-saga reformat
                language: system

            -   id: minos-microservice-saga-lint
                pass_filenames: false
                name: Lint minos-microservice-saga package
                entry: make --directory=packages/core/minos-microservice-saga lint
                language: system

            -   id: minos-microservice-saga-test
                pass_filenames: false
                name: Test minos-microservice-saga package
                entry: make --directory=packages/core/minos-microservice-saga test
                language: system

            -   id: minos-microservice-saga-docs
                pass_filenames: false
                name: Generate minos-microservice-saga documentation
                entry: make --directory=packages/core/minos-microservice-saga docs
                language: system

            -   id: minos-microservice-saga-build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-saga dist
                name: Generate build
                language: system
