files: ^packages/core/minos-microservice-saga/

repos:
    -   repo: local
        hooks:
            -   id: install
                pass_filenames: false
                name: Install dependencies
                entry: make --directory=packages/core/minos-microservice-saga install
                language: system

            -   id: reformat
                pass_filenames: false
                name: Reformat package
                entry: make --directory=packages/core/minos-microservice-saga reformat
                language: system

            -   id: lint
                pass_filenames: false
                name: Lint package
                entry: make --directory=packages/core/minos-microservice-saga lint
                language: system

            -   id: test
                pass_filenames: false
                name: Test package
                entry: make --directory=packages/core/minos-microservice-saga test
                language: system

            -   id: docs
                pass_filenames: false
                name: Generate documentation
                entry: make --directory=packages/core/minos-microservice-saga docs
                language: system

            -   id: build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-saga dist
                name: Generate build
                language: system
