version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/minos-microservice-aggregate"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/minos-microservice-common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/minos-microservice-cqrs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/minos-microservice-networks"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/minos-microservice-saga"
    schedule:
      interval: "weekly"
