default_stages: [ commit ]
repos:
    -   repo: local
        hooks:
            -   id: reformat
                pass_filenames: false
                name: Run code reformatting
                entry: make env-reformat
                language: system
            -   id: lint
                pass_filenames: false
                name: Run code lintting
                entry: make lint
                language: system
            -   id: test
                pass_filenames: false
                name: Run tests
                entry: make env-test
                language: system
