---
enabled: true
exclude:
  - "**/*.md"
  - ".idea/**/*"
  - "docs/**/*"
  - "**/*.in"
  - "Makefile"
  - ".github/workflows/**/*"
restylers:
  - name: black
    image: restyled/restyler-black:v19.10b0
    command:
      - black
    arguments: [" --line-length 120"]
    include:
      - "**/*.py"
    interpreters:
      - python
  - name: isort
    image: restyled/restyler-isort:v4.3.21
    command:
      - isort
    arguments: []
    include:
      - "**/*.py"
    interpreters:
      - python
  - name: reorder-python-imports
    image: 'restyled/restyler-reorder-python-imports:v2.4.0'
    command:
      - reorder-python-imports
      - '--exit-zero-even-if-changed'
    arguments: []
    include:
      - '**/*.py'
    interpreters:
      - python
