files: ^packages/core/minos-microservice-networks/

repos:
    -   repo: local
        hooks:
            -   id: minos-microservice-networks-install
                pass_filenames: false
                name: Install minos-microservice-networks dependencies
                entry: make --directory=packages/core/minos-microservice-networks install
                language: system

            -   id: minos-microservice-networks-reformat
                pass_filenames: false
                name: Reformat minos-microservice-networks package
                entry: make --directory=packages/core/minos-microservice-networks reformat
                language: system

            -   id: minos-microservice-networks-lint
                pass_filenames: false
                name: Lint minos-microservice-networks package
                entry: make --directory=packages/core/minos-microservice-networks lint
                language: system

            -   id: minos-microservice-networks-test
                pass_filenames: false
                name: Test minos-microservice-networks package
                entry: make --directory=packages/core/minos-microservice-networks test
                language: system

            -   id: minos-microservice-networks-docs
                pass_filenames: false
                name: Generate minos-microservice-networks documentation
                entry: make --directory=packages/core/minos-microservice-networks docs
                language: system

            -   id: minos-microservice-networks-build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-networks dist
                name: Generate build
                language: system
