files: ^packages/core/minos-microservice-cqrs/

repos:
    -   repo: local
        hooks:
            -   id: minos-microservice-cqrs-install
                pass_filenames: false
                name: Install minos-microservice-cqrs dependencies
                entry: make --directory=packages/core/minos-microservice-cqrs install
                language: system

            -   id: minos-microservice-cqrs-reformat
                pass_filenames: false
                name: Reformat minos-microservice-cqrs package
                entry: make --directory=packages/core/minos-microservice-cqrs reformat
                language: system

            -   id: minos-microservice-cqrs-lint
                pass_filenames: false
                name: Lint minos-microservice-cqrs package
                entry: make --directory=packages/core/minos-microservice-cqrs lint
                language: system

            -   id: minos-microservice-cqrs-test
                pass_filenames: false
                name: Test minos-microservice-cqrs package
                entry: make --directory=packages/core/minos-microservice-cqrs test
                language: system

            -   id: minos-microservice-cqrs-docs
                pass_filenames: false
                name: Generate minos-microservice-cqrs documentation
                entry: make --directory=packages/core/minos-microservice-cqrs docs
                language: system

            -   id: minos-microservice-cqrs-build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-cqrs dist
                name: Generate build
                language: system
