files: ^packages/core/minos-microservice-common/

repos:
    -   repo: local
        hooks:
            -   id: install
                pass_filenames: false
                name: Install dependencies
                entry: make --directory=packages/core/minos-microservice-common install
                language: system

            -   id: reformat
                pass_filenames: false
                name: Reformat package
                entry: make --directory=packages/core/minos-microservice-common reformat
                language: system

            -   id: lint
                pass_filenames: false
                name: Lint package
                entry: make --directory=packages/core/minos-microservice-common lint
                language: system

            -   id: test
                pass_filenames: false
                name: Test package
                entry: make --directory=packages/core/minos-microservice-common test
                language: system

            -   id: docs
                pass_filenames: false
                name: Generate documentation
                entry: make --directory=packages/core/minos-microservice-common docs
                language: system

            -   id: build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-common dist
                name: Generate build
                language: system
