files: ^packages/core/minos-microservice-common/

repos:
    -   repo: local
        hooks:
            -   id: minos-microservice-common-install
                pass_filenames: false
                name: Install minos-microservice-common dependencies
                entry: make --directory=packages/core/minos-microservice-common install
                language: system

            -   id: minos-microservice-common-reformat
                pass_filenames: false
                name: Reformat minos-microservice-common package
                entry: make --directory=packages/core/minos-microservice-common reformat
                language: system

            -   id: minos-microservice-common-lint
                pass_filenames: false
                name: Lint minos-microservice-common package
                entry: make --directory=packages/core/minos-microservice-common lint
                language: system

            -   id: minos-microservice-common-test
                pass_filenames: false
                name: Test minos-microservice-common package
                entry: make --directory=packages/core/minos-microservice-common test
                language: system

            -   id: minos-microservice-common-docs
                pass_filenames: false
                name: Generate minos-microservice-common documentation
                entry: make --directory=packages/core/minos-microservice-common docs
                language: system

            -   id: minos-microservice-common-build
                pass_filenames: false
                entry: make --directory=packages/core/minos-microservice-common dist
                name: Generate build
                language: system
