name: "Publish Documentation: minos-microservice-cqrs"

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.9-buster
    defaults:
      run:
        working-directory: packages/minos-microservice-cqrs

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4

      - name: Install dependencies
        run: make install

      - name: Generate documentation
        run: make docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
