name: "Release"

on:
  push:
    branches:
      - '*.*.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.9-buster

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Release Templates
        uses: softprops/action-gh-release@v1
        with:
          draft: true
